[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['cd main-app && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'cd main-app && gunicorn --bind 0.0.0.0:$PORT app:app'
